relativeurls        = true
baseurl             = "https://beckett.netlify.com/"   # Your domain name. Must end with "/"
languageCode        = "en-us"
title               = "Chamo Makato"
theme               = "hugo-theme-introduction"
enforce_ssl         = false
builddrafts         = false                             # Include pages with draft status of true
canonifyurls        = true                              # Turns relative urls into absolute urls
ignoreFiles         = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# disqusshortname   = "xxx"                             # Enable Disqus for comments
# googleAnalytics   = "xxx"

[params]
    bloghead            = ""                        # Full name shows on blog post pages
    firstname           = "Beckett"                # First name shows in introduction on main page
    tagline             = "Author and Illustrator"       # Appears after the introduction
    introheight         = "fullheight"                       # Input either 'medium' or 'large' or 'fullheight'
    themestyle          = "light"                        # Choose 'light' or 'dark'
    avatar              = "img/beckett.jpg"             # Path to image in static folder eg. img/avatar.png, or comment out to remove
    email               = "beckett.stephens@gmail.com"         # Shows in contact section, or leave blank to omit
    localtime           = false                          # Show your current local time in contact section
    timezone            = "America/New_York"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateform            = "Jan 2, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    cachebuster         = false                         # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description         = "I make books."        # Max 160 characters show in search results
    faviconfile         = "img/mc-favicon.ico"
    pygmentsStyle       = "monokai"                     # Choose theme: https://help.farbox.com/pygments.html
    pygmentsCodeFences  = true
    footertext          = "Powered by Hugo"                            # Text to show in footer (overrides default text)
    fadein              = false                          # Turn on/off the fade-in effect

    showblog            = true                          # Show Blog section on home page
    showprojects        = true                          # Show Projects section on home page
    showdocs            = true                          # Show Docs section on home page
    projectcolumns      = "2"                           # Choose "2" or "3" columns for projects section
    placeholderimg      = "/img/workday.jpg"            # For Projects without image
    showallposts        = true                         # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showlatest          = true                          # Show latest blog post summary
    sharebuttons        = true                          # On post pages, show share this social buttons

    # Share buttons
    sharetwitter        = true
    sharefacebook       = true
    sharepinterest      = false
    sharegoogleplus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/


